cmake_minimum_required(VERSION 2.8.6)

macro(add_subdir DIR SRC_LIST_NAME)
    set(SRC_LIST ${ARGV})
    list(REMOVE_AT SRC_LIST 0 1)
    set(${SRC_LIST_NAME} "")
    foreach(I ${SRC_LIST})
        set(${SRC_LIST_NAME} ${${SRC_LIST_NAME}} ${DIR}/${I})
    endforeach(I)
endmacro(add_subdir)

macro(add_subdir_exec DIR EXEC_NAME)
    set(SRC_LIST ${ARGV})
    list(REMOVE_AT SRC_LIST 0 1)
    add_subdir(${DIR} SRC_FILES ${SRC_LIST})
    add_executable(${EXEC_NAME} ${SRC_FILES})
endmacro(add_subdir_exec)

macro(add_subdir_lib DIR LIB_NAME LIB_TYPE)
    set(SRC_LIST ${ARGV})
    list(REMOVE_AT SRC_LIST 0 1 2)
    add_subdir(${DIR} SRC_FILES ${SRC_LIST})
    add_library(${LIB_NAME} ${LIB_TYPE} ${SRC_FILES})
endmacro(add_subdir_lib)

macro(add_module MODULE_NAME)
    set(SRC_LIST ${ARGV})
    list(REMOVE_AT SRC_LIST 0)
    add_subdir(${MODULE_NAME} SRC_FILES ${SRC_LIST})
    add_library(${MODULE_NAME} MODULE ${SRC_FILES})
    include_directories(${MODULE_NAME})
endmacro(add_module)
